[package]
name = "implied-vol"
version = "0.2.1"
authors = ["Hikaru Nakashima <nakashima.alg57@gmail.com>"]
description = "A pure rust implementation of Peter Jäckel's implied volatility calculation"
edition = "2021"
repository = "https://github.com/nakashima-hikaru/implied-vol"
license-file = "LICENSE"
keywords = ["finance"]
categories = ["finance"]

[features]
default = []
error-function = []
normal-distribution = []

[dependencies]

[dev-dependencies]
rand = "0.8.5"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
pedantic = "warn"
cargo = "warn"

[profile.bench]
lto = true